server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=kratos sslmode=disable TimeZone=Asia/Shanghai"
    max_idle_conns: 10
    max_open_conns: 50
    conn_max_lifetime: 1800s
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
