server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  pprof:
    enabled: false
    addr: ":6060"
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    dial_timeout: 2s
    read_timeout: 0.2s
    write_timeout: 0.2s
    pool_size: 10
log:
  format: json
  level: info
  add_source: true
  # output_path: ""
telemetry:
  otlp_endpoint: "localhost:4317"
  sampling_rate: 1.0  # 0.0~1.0, 1.0=全量采样, 生产建议 0.1
